<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <DebugType>embedded</DebugType>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <PublishRelease>true</PublishRelease>
    <IsTestProject>false</IsTestProject>
    <PackAsTool>false</PackAsTool>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Eigenverft.NetLib.Configuration.Binding\Eigenverft.NetLib.Configuration.Binding.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\Eigenverft.NetLib.Configuration.Diagnostics\Eigenverft.NetLib.Configuration.Diagnostics.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\Eigenverft.NetLib.Configuration.Sets\Eigenverft.NetLib.Configuration.Sets.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\Eigenverft.NetLib.Configuration.Sources\Eigenverft.NetLib.Configuration.Sources.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\Eigenverft.NetLib.Configuration.SwitchableJson\Eigenverft.NetLib.Configuration.SwitchableJson.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\Eigenverft.NetLib.Configuration.Values\Eigenverft.NetLib.Configuration.Values.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\Eigenverft.NetLib.Configuration.WritebackJson\Eigenverft.NetLib.Configuration.WritebackJson.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\Eigenverft.NetLib.Hosting.DirectoryLayout\Eigenverft.NetLib.Hosting.DirectoryLayout.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\Eigenverft.NetLib.Hosting.SelfHttpWarmup\Eigenverft.NetLib.Hosting.SelfHttpWarmup.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\Eigenverft.NetLib.Logging.Bootstrap\Eigenverft.NetLib.Logging.Bootstrap.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\Eigenverft.NetLib.Logging.Deferred\Eigenverft.NetLib.Logging.Deferred.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\Eigenverft.NetLib.Networking\Eigenverft.NetLib.Networking.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\Eigenverft.NetLib.Security.Certificates\Eigenverft.NetLib.Security.Certificates.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\Eigenverft.NetLib.Security.DataProtection\Eigenverft.NetLib.Security.DataProtection.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\Eigenverft.NetLib.Security.MachineBinding\Eigenverft.NetLib.Security.MachineBinding.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\Eigenverft.NetLib.Transformations\Eigenverft.NetLib.Transformations.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>
  <Target Name="CopyToLocalPackages" AfterTargets="Pack" Condition="'$(LocalPackagesDir)'!='' and '$(IsPackable)' == 'true'">
    <Message Text="Copy $(PackageOutputPath)/$(PackageId).$(PackageVersion).nupkg to $(LocalPackagesDir)" Importance="high" />
    <Copy SourceFiles="$(PackageOutputPath)/$(PackageId).$(PackageVersion).nupkg" DestinationFolder="$(LocalPackagesDir)" />
  </Target>
  <Import Project="Build/SourceControlState.targets" />
  <Import Project="Build/ImportSdkTargets.targets" />
</Project>
